#include<iostream>
using namespace std;
main()
{
cout<<"      .             .             .          "<<endl;
cout<<"       .             .             .         "<<endl;
cout<<"        .             .             .        "<<endl;
cout<<"      .             .             .          "<<endl;
cout<<"     .             .             .           "<<endl;
cout<<"      .             .             .          "<<endl;
cout<<"       .             .             .         "<<endl;
cout<<"    -----------------------------------      "<<endl;
cout<<"     .                              .        "<<endl;
cout<<"      .                            .         "<<endl;
cout<<"       .                          .          "<<endl;
cout<<"        .                        .           "<<endl;
cout<<"          .                     .            "<<endl;
cout<<"          ----------------------             "<<endl;
cout<<"   WELCOME TO THE FOOD :)Y APPLICATION#      "<<endl;
}